'use client';

export default function ProfileSocialPage() {
  return (
    <div>
      <p>VIDEO</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
    </div>
  );
}
