"use client";

export default function ChannelSocialPage() {
  return (
    <div>
      <p>VIDEO</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
    </div>
  );
}
