"use client";

export default function ProfileSocialPage() {
  return (
    <div>
      <p>ABOUT</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
      <p>ajksdhakjshdkj</p>
    </div>
  );
}
